### ISSUE TITLE
Stop PLNnetwork function when "blocked" (enhancement)

### ISSUE THREAD

**Issue by mjcros** [jchiquet/PLNmodels#18] opened 2018-10-11 13:43 UTC
May be, stop after a given running duration ...

**Comment by mjcros** [comment] 2018-10-12 07:10
Example  of  counts:
0,0,0,5,20,10,0,0,0,0,8,6,23,11,0,0,0,0,12,0,0,0,8,6,5,0,6,4,0,0,6,8,5,0,0,0,0,0,0,0,0,9,8,0,5,0,0,0,6,0,22,0,3,0,5,0,27,0,5,0,37,7,5,3,0,0,0,0
12,0,5,24,12,6,0,5,3,32,0,17,7,11,16,12,0,7,0,0,0,5,8,5,9,0,11,5,18,8,6,6,12,0,7,0,0,23,6,6,0,18,7,7,5,6,7,0,22,8,7,1,12,3,8,5,5,14,5,0,0,6,0,0,6,0,17,0
14,0,29,2,7,9,0,0,5,7,6,8,2,13,0,12,10,4,1,15,0,3,8,1,8,19,12,7,13,8,13,13,10,7,0,5,0,0,8,0,0,7,4,4,7,0,24,0,2,11,7,1,0,12,10,4,1,15,0,6,0,10,0,0,14,3,17,13
12,2,7,16,31,5,4,3,3,7,16,10,6,13,8,12,5,18,3,8,5,7,0,5,9,18,9,4,13,8,11,10,5,4,2,10,2,4,7,6,0,4,5,12,6,5,9,0,8,8,0,2,19,7,11,6,0,9,5,0,2,11,0,1,27,0,10,6
10,1,6,3,6,8,3,5,9,5,10,4,4,10,17,0,8,4,13,27,17,5,0,7,5,10,7,35,20,0,5,7,5,8,15,5,10,7,0,0,0,8,12,9,8,0,38,0,5,8,0,4,3,7,5,4,0,14,5,23,5,6,2,2,17,6,14,17
10,8,7,5,3,5,20,16,3,17,4,1,6,8,12,9,5,35,15,9,16,8,0,3,7,6,8,4,12,11,5,6,10,4,11,9,5,0,12,19,22,4,6,20,8,17,6,17,11,0,7,24,14,8,6,4,1,14,19,6,2,7,8,12,8,3,0,9
10,1,8,5,0,8,6,9,17,13,12,4,7,9,18,12,5,7,4,12,3,7,0,5,8,10,7,4,6,11,6,6,10,13,14,9,4,4,21,0,8,7,4,23,5,11,1,0,4,0,0,3,0,11,9,6,1,11,5,22,14,6,10,2,15,5,5,15
10,11,6,8,0,17,11,3,9,7,0,9,4,7,7,18,5,9,5,11,21,3,8,6,6,15,12,4,6,12,6,6,15,6,5,5,15,12,15,12,9,9,16,9,5,17,4,23,4,8,0,27,19,8,8,9,1,7,5,0,15,6,8,5,5,4,5,17
10,5,5,6,0,6,9,2,8,7,4,10,7,3,10,6,11,4,2,12,0,15,8,7,7,2,5,3,7,8,5,7,0,15,25,8,4,0,22,0,6,0,6,11,7,14,2,6,4,8,0,0,3,6,5,10,1,7,19,0,4,6,9,9,4,16,0,6
0,2,3,4,0,5,11,6,3,0,4,8,4,4,0,0,5,0,10,0,0,15,12,7,5,4,6,3,0,8,5,7,0,4,0,5,15,8,0,0,6,4,5,0,5,5,3,9,3,0,7,3,3,7,5,8,3,0,6,6,2,6,12,6,0,5,5,4
10,1,4,2,0,6,15,10,9,5,0,4,4,3,12,0,10,5,3,6,13,10,23,9,7,2,3,4,6,8,5,6,0,4,22,0,10,6,8,6,25,4,5,5,5,11,1,11,7,8,0,5,9,8,5,12,5,10,0,6,5,6,11,9,3,3,10,4
0,2,3,4,3,6,2,8,7,0,0,1,4,3,0,0,10,0,8,0,3,10,8,5,5,2,4,3,0,0,6,6,5,8,0,10,6,8,0,6,3,9,5,0,6,5,1,0,4,10,14,1,3,6,5,4,4,0,8,8,6,6,8,8,0,16,0,9
0,9,6,7,5,3,4,8,12,0,12,3,4,3,0,6,6,4,11,0,13,3,8,8,6,4,3,3,0,8,6,6,24,17,0,5,8,12,0,25,9,4,5,0,5,11,1,11,4,12,7,5,3,7,6,13,2,0,8,6,3,6,8,10,0,12,5,0
0,11,5,5,7,4,2,7,10,0,12,2,2,3,0,6,8,5,5,0,8,9,12,9,8,2,5,10,0,10,7,6,0,4,0,10,9,4,0,6,5,9,3,0,23,0,2,11,5,9,17,6,3,7,6,13,1,0,5,8,2,6,9,18,0,3,5,0
0,45,6,0,0,0,0,8,0,0,0,13,8,0,0,0,5,0,3,0,0,0,0,9,6,0,0,7,0,0,6,0,0,0,0,0,5,0,0,0,3,0,6,0,0,0,1,11,11,10,10,17,4,1,6,3,8,0,5,9,0,6,6,11,0,7,0,0
0,3,0,3,6,1,11,11,0,0,14,0,8,2,0,6,10,0,6,0,0,0,0,7,0,5,3,0,0,0,0,0,0,4,0,17,6,10,0,12,3,4,4,0,0,0,0,0,0,0,0,1,3,3,0,0,43,0,0,0,3,0,3,4,0,16,10,0

**Comment by jchiquet** [comment] 2018-10-16 10:33
Hi @mjcros ,

Concerning your question, on the last master version of PLNmodels (0.5.4001)

- I added a maxtime option (Default set to -1) in PLN, PLNPCA and PLNnetwork which controls the amount of time (in second) nlopt is going to perform optimization before ti stops. So you can use it on your data like taht 

```r
library(PLNmodels)
data(trichoptera)
models <- PLNnetwork(Abundance ~ 1, data = trichoptera)
hurry <- PLNnetwork(Abundance ~ 1, data = trichoptera, control_main = list(maxtime = 1e-4))
```

- I have been playing with your data. PLNPCA and PLN work just fine 
```r
library(tidyverse)
library(PLNmodels)

data <- read_delim("~/Desktop/counts_failing.csv", delim = ",", col_names = FALSE) %>% as.matrix()

myPCA <- PLNPCA(data ~ 1, ranks = 1:10)
myPCA$plot()
myPCA$getBestModel("ICL")$plot_PCA()

myPLN <- PLN(data ~ 1)
myPLN$plot()
```

However, it is true that PLNnetwork is running for a long time... It turns out after investigation that it is due to the underlying Graphical Lasso algorithm from the glasso package :  it gets stuck at some point... so it is something that I cannot control. I am going to look to an alternative to the glasso package.

It is probably due to the fact that the problem is particularly ill-conditioned. Did you normalized you count data in some way?

**Comment by jchiquet** [comment] 2018-10-16 15:14
Ok,

I have now replaced glasso by glassoFast in the master version. Indeed, glassoFast is more stable but I realize that another issue was causing instability and everlasting computation...

The default in PLNnetwork was to not penalize the diagonal of the inverse covariance matrix. It seems more relevant from the statistical point of view. Still, the optimization problem in Glasso is more instable. with the package glasso, it was completly stuck. With glassofast, at least it works. 

Still, I changed the default param penalize_diagonal to TRUE : the  (variational) loglikelihood, BIC and other criteria are more smooth. So you can now run the following, everything is working (hopefully !)

```r
library(tidyverse)
library(PLNmodels)

data <- read_delim("~/Desktop/counts_failing.csv", delim = ",", col_names = FALSE) %>% as.matrix()

myPCA <- PLNPCA(data ~ 1, ranks = 1:10)
myPCA$plot()
myPCA$getBestModel("ICL")$plot_PCA()

myPLN <- PLN(data ~ 1)
myPLN$plot()

myNetworks <- PLNnetwork(data ~ 1)
myNetworks$plot()
myNetworks$getBestModel('EBIC')$plot_network()
```

**Comment by jchiquet** [comment] 2018-10-24 05:15
If no more comment, I am closing this thread.

**Closed by jchiquet** 2018-10-24 05:15 UTC
